#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

#define TILE_SIZE 32
#define TILE_SIZE_OP 24

#define SPACE_BAR 2
#define ARROW_UP 3
#define ARROW_DOWN 4
#define ARROW_LEFT 1
#define ARROW_RIGHT -1
#define SWAP 5

#define COMMAND_MESSAGE 12
#define CONNECT_MESSAGE 13
#define STATE_MESSAGE 14
#define START_MESSAGE 15
#define WIN_MESSAGE 16
#define LOSE_MESSAGE 17
#define RESULTS_MESSAGE 18

#endif
